{
 "title": "General Summary",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "AWS Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "AWS ALB Status Codes",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "AvailabilityZone": "*", "TargetGroup": "*" },
     "label": "2xx",
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "AvailabilityZone": "*", "TargetGroup": "*" },
     "label": "3xx",
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "AvailabilityZone": "*", "TargetGroup": "*" },
     "label": "4xx",
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "AvailabilityZone": "*", "TargetGroup": "*" },
     "label": "5xx",
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "AWS ALB Target Response Time",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "AvailabilityZone": "*", "TargetGroup": "*" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Nginx Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Nginx Request Status Rate (30m)",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_requests[30m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Percentile Response Times (Total)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[2m])) by (le))",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[2m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[2m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}