nodeSelector:
  role: monitoring

persistence:
  enabled: true
  storageClassName: gp2

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true
      - name: CloudWatch
        type: cloudwatch
        jsonData:
          authType: default
          defaultRegion: eu-west-2

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "grafana-dashboards-kubernetes"
        orgId: 1
        folder: "Kubernetes"
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
      - name: "aws-dashboards"
        orgId: 1
        folder: "AWS"
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/aws-dashboards
      - name: "nginx-dashboards"
        orgId: 1
        folder: "NGINX"
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/nginx-dashboards
dashboards:
  grafana-dashboards-kubernetes:
    k8s-system-api-server:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
      token: ""
    k8s-system-coredns:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
      token: ""
    k8s-views-global:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
      token: ""
    k8s-views-namespaces:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
      token: ""
    k8s-views-nodes:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
      token: ""
    k8s-views-pods:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
      token: ""
  aws-dashboards:
    eks:
      url: https://raw.githubusercontent.com/monitoringartist/grafana-aws-cloudwatch-dashboards/refs/heads/master/aws-eks/aws-eks.json
      token: ""
    alb:
      url: https://raw.githubusercontent.com/monitoringartist/grafana-aws-cloudwatch-dashboards/refs/heads/master/aws-elb/aws-elb-application-lb.json
      token: ""
    elb-classic:
      url: https://raw.githubusercontent.com/monitoringartist/grafana-aws-cloudwatch-dashboards/refs/heads/master/aws-elb/aws-elb-classic-lb.json
      token: ""
  nginx-dashboards:
    nginx-ingress:
      url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/refs/heads/main/deploy/grafana/dashboards/nginx.json
      token: ""
